# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tId-CY1MfKuXbgesCVXQkBbpHRFz9Wq9
"""

age = 10
print("memory of age",id(age))
x = age
print("memory of x",id(x))
x = 20
print("new memory of x",id(x))

mylist= [10,20,"abc"]
print(type(mylist))
print(mylist[1])
mylist.append(80)
print(mylist)
mylist.pop()
print(mylist)
out = mylist.pop()
print(out)
print(mylist)

list1 = [10,20,30,40,50]
for i in list1:    #execute loop directly => iterable
#not for use
    print(i)

list1= [10,21,32,42,57,63,73,89]
for i in range(0,len(list1)):
     if (list1[i] % 2!=0):
        list2.append(list1[i])
        print(list1[i])

list1= [10,21,32,42,57,63,73,89]
list2 = []
for i in range(0,len(list1)):
     if list1[i] < 40:
        list2.append(list1[i])
print(list2)

