# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZG_VWlWvQM5EOmGLTCIsglfqjmZmO9F
"""

def greeting(z):
    print("hey user i welcom you on board",z)

def factors(num):
    for i in range(1,num+1):
        if(num%i==0):
            print("factors",num,"is",i,)
factors(8)

factors(7)

def func(id,name,salary):
    print(f"id is {id} name is {name} and salary is {salary}")
func(1,"yash",900)
func("yash",1,900)
func(id = 1,name = "yash",salary = 900)

func(1,"yash",900)
func("yash",1,900)
func(id = 1,name = "yash",salary = 900)

def func(id,name,salary):
    print(f"id is {id} name is {name} and salary is {salary}")
func(10,salary = 10000,name=" virendra")

def func(id,name,salary):
    print(f"id is {id} name is {name} and salary is {salary}")
func(name = "virendra",id = 10,salary = 10000)

number1 = 23
number2 = 12
if(number1 > number2):
    Value = number1
else:
    Value = number2
while(True):
    if(Value % number1 == 0 and Value % number2 == 0):
        print("The LCM of ",
              number1, ",", number2, "=", Value)
        break
    Value = Value + 1

def func(id,name,salary):
    print(f"id is {id} name is {name} and salary is {salary}")

func(10,name="abhishek", salary = 633)



def func(x):
    return (x+10)
a = func(5)
print("a",a)

