# -*- coding: utf-8 -*-
"""Untitled58.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLAC0WfQeXT1wJ3p9FrE2Bgb_Oo-AFFV
"""

def tab():
    print("hello")

tab()

def add(a,b):
    result = a + b
    print(result)

add(3,4)

def facebook(**kwargs):
    print(kwargs)

facebook(name="tushar")
facebook(name="tushar",college = "abc")

def facebook(*args):
    print(args)

facebook("tushar","abc","gap")

def func(x):
    print(x+10)
    return 1000

out = func(15)
print("after function",out)

a = lambda x:x+10
a(15)
#lambda paramter : expression

(lambda x:x+10)(20)

a = lambda x: x[0:2]
for i in " hey hello user ".split(" "):
    print(i)
    print(a(i))

ls = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
new = []
a=lambda x:x%2==0
for i in ls:
    if(i%2==0):
        if(a(i)):
            new.append(i)
print(new)

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

even_numbers = [x for x in numbers if (lambda x: x % 2 == 0)(x)]

print(even_numbers)

def fun():
    print("hello")
a =fun()
print(a)

d = {lambda x:x+10}
print(d)

student = {
    "func": lambda x:x+10,
    "name": "Tushar",
    "age": 22,
    "course": "Data Engineering",
    "city": "Jaipur"
}

print(student["func"](10))