# -*- coding: utf-8 -*-
"""Untitled75.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TgVYxhiAyVNzgiQkopsFM3aepNULK0dK
"""

class A:
    dept="HR"
    def __init__(self,age):
        self.age=age       #instance variable

    def userinfo(self):     #self => instance method have self as first parameter
        self.age=500
        self.dept="IT"
        print("instance variable",self.age,self.dept)

a1 = A(1000)
a2 = A(600)
a1.userinfo()
a2.dept

class A:
    dept="HR"
    def __init__(self,age):
        self.age=age       #instance variable

    def userinfo(self):     #self => instance method have self as first parameter
        self.age=500
        self.dept="IT"
        print("instance variable",self.age,self.dept)
    @staticmethod
    def adddata(salary):
        print("salary",salary*1.1)

a1=A(1000)
a1.adddata(9000)

class dollar:
    def __init__(self,amount):
        self.amount=amount
    def totalamount(self):
        print(f"dollar class has amount{self.amount}")

class euro(dollar):
    def __init__(self,x):
        super(). __init__(x)

    def info(self):
        super().totalamount()

e1=euro(10)
e1.info()

class dollar:
    symbol="$"
    def __init__(self,amount):
        self.amount=amount
    @classmethod
    def totalamount(cls):
        print(f" {cls} class has amount,{cls.symbol}")

d1 = dollar(10)
d1.totalamount()

class dollar:
    def __init__(self,amount):
        self.amount=amount

    def __repr__(self):
        return f"dollar class has amount{self.amount}"

d1=dollar(100)
print(d1)