# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZ_dSeB0znzA1ORRrO7VjeYL7mKluDEE
"""

try:
    x=50
    x=x/5
    x+"hey"
    print("hey")
except (NameError,TypeError) as e:  #exception this is a class
    print("error:",e)

try:
    x=50
    x=x/5
    "hey"[10]
    x+"hey"
    print("hey")
except (NameError,TypeError) as e:  #exception this is a class
    print("error:",e)
except Exception as e:
    print("all other error :",e)

try:
    x=50
    x=x/5
    try:
        "hey"[10]
    except:
        print("neste error handled")
    x+"hey"
    print("hey")
except (NameError,TypeError) as e:  #exception this is a class
    print("error:",e)
except Exception as e:
    print("all other error :",e)

def fun(x):
    assert x>10
    print("hey")
fun(7)

try:
    a=9
    if(a>10):
        raise ValueError
    else:
        print("a value",a)
except:
    print("value error to be handle")