# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsQ1KCvsHGecmNunlz6CTZGjZrvjkac2
"""

list comphrehension,dictionary,set comphrehension

[i for i in range(1,12) if i%2==0 and i%3==0]

{i:i**2 for i in range(1,12)}

[(i,j) for i in range(1,5) for j in range(5,8)]

