# -*- coding: utf-8 -*-
"""Untitled77.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nI07xFHXx_wHeeA-RhwG5qrLmrjiVm66
"""

def func(num):
    print("first liner")
    yield 1
    print("hey")
    yield 2

x = func(10)
print(next(x))

next(x)

next(x)

next(x)

def fibonacci_gen(n):
    a, b = 0, 1
    count = 0
    while count < n:
        yield a
        a, b = b, a + b
        count += 1

gen = fibonacci_gen(10)
for num in gen:
    print(num)

def func(num):
    print("first liner")
    i = 0
    while(i<5):
        print("hey ",i)
        i+=1
        yield "ABC"

gen = func(10)
for i in gen:
    print(i)

# map,filter => high order functions
y = map(lambda x:x**2,[1,2,3,4,5])
next(y)

next(y)

next(y)

y = filter(lambda x:x%2==0,[1,2,3,4,5])
list(y)

y = map(lambda x:x**2,[25,14,63,1])
list(y)