# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XnnQdavVCPF_DGQt8kJaWT_Ok6qt0CZb
"""

# dictionary
#[10,20,30,40,50]
mylist=[10,20,10,40,30,50]
mydictionary={}
for i in mylist:
    if i in mydictionary:
        mydictionary[i]=mydictionary[i]+1
    else:
        mydictionary[i]=1
print(mydictionary)

d={10:1}
if(20 in d):
    d[10]=d[10]+1
else:
    d[20]=1
print(d)

s="abc"
for i in range(0,3):
    data = ""
    for j in range(0,i):
        print(i,j,s[j])

        data = data + s[j]
        print(data)

s="abc"
for i in range(0,4):
    data = ""
    for j in range(0,i):
        print(i,j,s[j])

        data = data + s[j]
    print(data)

s = "abcd"
d={}
for i in range(0,4):
    data=""
    for j in range(0,i):
        data=data+s[j]
        if j in d:
            d[data]=d[data]+1
        else:
            d[data]=1
print(d)

a = "abc"
d = {}
for i in range(0,4):
    data=""
    for j in range(1,i):
        data=data+a[j]
        if j in d:
            d[data]=d[data]+1
        else:
            d[data]=1
print(d)

mylist = [0,1,2,4,7,11,14,15]
target = 9
my={}
for index,data in enumerate(mylist):
    my[data]=index
for i in mylist:
    if(target-i in my):
        print(i,my[target-i])

