# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VjatGAWiIYT-nZiXk9LO-ENFszlCfZq0
"""

x = 10,20
print(type(x))

x = (10,20,"abc")
print(type(x))

x = (10,20,"abc",10,10,40,90)
print(x.count(10))
print(x.index(40))
#x[0]= 19 we cant do insert,updat,delete

#dictionary : datatype ,use to store data but
'''
without index position
data is store => key,values
key is unique
value can be unique/dublicate
dictionary are mutuable
-no index
key => data(unique)
--bill no: 101
--101=> product,kitna,kab(value)
key:value
dictionary=>

mydictionary={101:'virendra','salary':200000,'email':'virendra@gmail.com'}
print(mydictionary)

mydictionary={101:'virendra','salary':200000,'email':'virendra@gmail.com'}
print(mydictionary["email"])
x = mydictionary.pop(101)
print(mydictionary,x)

mydictionary= {10:"a",20:"b"}
for i in mydictionary:
    print(i,mydictionary[i])

mydictionary= {10:"a",20:"b"}
for i in mydictionary.values():
    print(i)

mydictionary={10:"a","amount":100}
mydictionary["amount"]+5
print(mydictionary)

s = "Raj5"
d = {'total':0}
for i in s:
    d["total"]+=1
print(d)



mydictionary={}
for i in "abc":
    mydictionary[i]=1
print(mydictionary)

