# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SUmwbuN7FarWPXkg4cQrcuUViyBlOG7l
"""

my_list = [60,20,30,40,50]
start = 0
end = len(my_list) - 1
while start < end:
    my_list[start], my_list[end] = my_list[end], my_list[start]
    start += 1
    end -= 1
print(my_list)

my_list = [10,20,30,40,50]
start = 0
end=len(my_list)-1
while (start!=end):
    temp = my_list[start]
    my_list[start]=my_list[end]
    my_list[end]=temp
    start+=1
    end-=1
print(my_list)

my_list = [3,5,10,20,30,40,50]
for i in range(0,len(my_list)):
    for j in range(i+1,len(my_list)):
        print(i,j,my_list[i],my_list[j])
        temp = my_list[i]
        my_list[i] = my_list[j]
        my_list[j] = temp
        print("after change =>",i,j,my_list[i],my_list[j])
print(my_list)

my_list = [3,5,10,20,30,40,50]
_list = [ ]
i = len(my_list)-1
while i>=0:
    _list.append(my_list[i])
    j =i
    while j==i:
        _list.append(my_list[i])
        j-=1
    i-=1
print(my_list)